python39Packages.Cython: 0.29.22 -> 0.29.24
Required to build numpy

RuntimeError: Building NumPy requires Cython >= 0.29.24, found 0.29.22 at /nix/store/7qrl7hhzvbmd966b61w3n0dkamn863gn-python3.9-Cython-0.29.22/lib/python3.9/site-packages/Cython/init.py